import type { App } from "vue";
import {
  IconApps,
  IconCheckCircleFill,
  IconClose,
  IconCloseCircle,
  IconCloudDownload,
  IconCopy,
  IconDelete,
  IconDown,
  IconDownload,
  IconEdit,
  IconExclamationCircleFill,
  IconExport,
  IconEye,
  IconFile,
  IconFolder,
  IconFolderDelete,
  IconFullscreen,
  IconFullscreenExit,
  IconHome,
  IconImport,
  IconLanguage,
  IconLeft,
  IconLock,
  IconMenuFold,
  IconMenuUnfold,
  IconMoonFill,
  IconNotification,
  IconPlayArrowFill,
  IconPlus,
  IconQuestionCircleFill,
  IconRefresh,
  IconRight,
  IconSave,
  IconSearch,
  IconSettings,
  IconSkin,
  IconSunFill,
  IconSwap,
  IconUp,
  IconUpload,
  IconUser
} from "@arco-design/web-vue/es/icon";

const icons = [
  IconApps,
  IconCheckCircleFill,
  IconClose,
  IconCloseCircle,
  IconCloudDownload,
  IconCopy,
  IconDelete,
  IconDown,
  IconDownload,
  IconEdit,
  IconExclamationCircleFill,
  IconExport,
  IconEye,
  IconFile,
  IconFolder,
  IconFolderDelete,
  IconFullscreen,
  IconFullscreenExit,
  IconHome,
  IconImport,
  IconLanguage,
  IconLeft,
  IconLock,
  IconMenuFold,
  IconMenuUnfold,
  IconMoonFill,
  IconNotification,
  IconPlayArrowFill,
  IconPlus,
  IconQuestionCircleFill,
  IconRefresh,
  IconRight,
  IconSave,
  IconSearch,
  IconSettings,
  IconSkin,
  IconSunFill,
  IconSwap,
  IconUp,
  IconUpload,
  IconUser
];

export function registerArcoIcons(app: App) {
  icons.forEach(icon => {
    if (icon.name) {
      app.component(icon.name, icon);
    }
  });
}
