package config

// Code generated by "go_sleep_admin config sync" from config/env/dev.yml; DO NOT EDIT.

type AliyunSMSConfig struct {
	AccessID     string `mapstructure:"sms_access_id"`
	AccessSecret string `mapstructure:"sms_access_secret"`
	SignName     string `mapstructure:"sms_sign_name"`
	TemplateCode string `mapstructure:"sms_template_code"`
}

type AliyunConfig struct {
	SMS AliyunSMSConfig `mapstructure:",squash"`
}

type AppConfig struct {
	Domain              string `mapstructure:"domain"`
	Host                string `mapstructure:"host"`
	EnableHTTPS         bool   `mapstructure:"ishttps"`
	Mode                string `mapstructure:"mode"`
	Name                string `mapstructure:"name"`
	Port                string `mapstructure:"port"`
	ReadTimeoutSeconds  int    `mapstructure:"readtimeout"`
	Timezone            string `mapstructure:"timezone"`
	WriteTimeoutSeconds int    `mapstructure:"writertimeout"`
}

type BaiduVoiceConfig struct {
	APIKey    string `mapstructure:"apikey"`
	AppID     string `mapstructure:"appid"`
	SecretKey string `mapstructure:"secretkey"`
}

type BaiduConfig struct {
	Voice BaiduVoiceConfig `mapstructure:"voice"`
}

type DatabaseConfig struct {
	DBType         string `mapstructure:"dbtype"`
	Host           string `mapstructure:"host"`
	MaxIdleConn    int    `mapstructure:"maxidleconn"`
	MaxLifeSeconds int    `mapstructure:"maxlifeseconds"`
	MaxOpenConn    int    `mapstructure:"maxopenconn"`
	Name           string `mapstructure:"name"`
	Password       string `mapstructure:"password"`
	Port           string `mapstructure:"port"`
	Username       string `mapstructure:"username"`
}

type ElasticsearchConfig struct {
	Debug  int    `mapstructure:"debug"`
	Host   string `mapstructure:"host"`
	Pass   string `mapstructure:"pass"`
	Port   string `mapstructure:"port"`
	Scheme string `mapstructure:"scheme"`
	User   string `mapstructure:"user"`
}

type EmailConfig struct {
	Alias string `mapstructure:"alias"`
	Host  string `mapstructure:"host"`
	Pass  string `mapstructure:"pass"`
	Port  int    `mapstructure:"port"`
	User  string `mapstructure:"user"`
}

type JWTConfig struct {
	Secret         string `mapstructure:"secret"`
	Timeout        int    `mapstructure:"timeout"`
	RefreshTimeout int    `mapstructure:"refresh_timeout"`
}

type LLMConfig struct {
	APIKey             string `mapstructure:"api_key"`
	MaxHistoryMessages int    `mapstructure:"max_history_messages"`
	MaxMessageChars    int    `mapstructure:"max_message_chars"`
	Model              string `mapstructure:"model"`
	Provider           string `mapstructure:"provider"`
	RedisDB            int    `mapstructure:"redis_db"`
	SessionTTLSeconds  int    `mapstructure:"session_ttl_seconds"`
	SystemPrompt       string `mapstructure:"system_prompt"`
	TimeoutSeconds     int    `mapstructure:"timeout_seconds"`
}

type LogConfig struct {
	Compress      int    `mapstructure:"compress"`
	ConsoleStdout int    `mapstructure:"consolestdout"`
	FileStdout    int    `mapstructure:"filestdout"`
	Level         string `mapstructure:"level"`
	LocalTime     int    `mapstructure:"localtime"`
	MaxAge        int    `mapstructure:"maxage"`
	MaxBackups    int    `mapstructure:"maxbackups"`
	MaxSize       int    `mapstructure:"maxsize"`
	Path          string `mapstructure:"path"`
	SQL           int    `mapstructure:"sql"`
}

type NewsConfig struct {
	AppID     string `mapstructure:"appid"`
	AppSecret string `mapstructure:"appsecret"`
	FSURL     string `mapstructure:"fsurl"`
}

type RedisConfig struct {
	Addr     string `mapstructure:"addr"`
	DBs      []int  `mapstructure:"dbs"`
	Password string `mapstructure:"password"`
	Prefix   string `mapstructure:"prefix"`
}

type SMSConfig struct {
	Enabled bool `mapstructure:"enabled"`
}

type SSLConfig struct {
	Key string `mapstructure:"key"`
	PEM string `mapstructure:"pem"`
}

type UploadOSSConfig struct {
	Region          string `mapstructure:"region"`
	Endpoint        string `mapstructure:"endpoint"`
	Bucket          string `mapstructure:"bucket"`
	AccessKeyID     string `mapstructure:"access_key_id"`
	AccessKeySecret string `mapstructure:"access_key_secret"`
	SessionToken    string `mapstructure:"session_token"`
	ObjectPrefix    string `mapstructure:"object_prefix"`
	PublicBaseURL   string `mapstructure:"public_base_url"`
	DisableSSL      bool   `mapstructure:"disable_ssl"`
	UseInternal     bool   `mapstructure:"use_internal_endpoint"`
	UseCName        bool   `mapstructure:"use_cname"`
}

type UploadCOSConfig struct {
	Region        string `mapstructure:"region"`
	BucketURL     string `mapstructure:"bucket_url"`
	SecretID      string `mapstructure:"secret_id"`
	SecretKey     string `mapstructure:"secret_key"`
	PathStyle     bool   `mapstructure:"path_style"`
	ObjectPrefix  string `mapstructure:"object_prefix"`
	PublicBaseURL string `mapstructure:"public_base_url"`
}

type UploadOBSConfig struct {
	Endpoint        string `mapstructure:"endpoint"`
	Bucket          string `mapstructure:"bucket"`
	AccessKeyID     string `mapstructure:"access_key_id"`
	AccessKeySecret string `mapstructure:"access_key_secret"`
	ObjectPrefix    string `mapstructure:"object_prefix"`
	PublicBaseURL   string `mapstructure:"public_base_url"`
}

type UploadConfig struct {
	Driver      string          `mapstructure:"driver"`
	LocalDir    string          `mapstructure:"local_dir"`
	PublicPath  string          `mapstructure:"public_path"`
	AllowedExts []string        `mapstructure:"allowed_exts"`
	MaxSizeMB   int64           `mapstructure:"max_size_mb"`
	OSS         UploadOSSConfig `mapstructure:"oss"`
	COS         UploadCOSConfig `mapstructure:"cos"`
	OBS         UploadOBSConfig `mapstructure:"obs"`
}

type Config struct {
	Env           string              `mapstructure:"-"`
	Aliyun        AliyunConfig        `mapstructure:"aliyun"`
	App           AppConfig           `mapstructure:"application"`
	Baidu         BaiduConfig         `mapstructure:"baidu"`
	Database      DatabaseConfig      `mapstructure:"database"`
	Elasticsearch ElasticsearchConfig `mapstructure:"elasticsearch"`
	Email         EmailConfig         `mapstructure:"email"`
	JWT           JWTConfig           `mapstructure:"jwt"`
	LLM           LLMConfig           `mapstructure:"llm"`
	Log           LogConfig           `mapstructure:"log"`
	News          NewsConfig          `mapstructure:"news"`
	Redis         RedisConfig         `mapstructure:"redis"`
	SMS           SMSConfig           `mapstructure:"sms"`
	SSL           SSLConfig           `mapstructure:"ssl"`
	Upload        UploadConfig        `mapstructure:"upload"`
}
